// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txjfuijuwdmhptxdudcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4amZ1aWp1d2RtaHB0eGR1ZGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTUxMjcsImV4cCI6MjA2OTg3MTEyN30.aG5pcLhG0OfItKa5kS0Cx8RV-eNbTihWyO_RMLyB628";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});